### ISSUE TITLE
Make json as it should be :P

### ISSUE THREAD

**Issue by SamuraiPolix** [SamuraiPolix/openbible-verse-scraper#2]
**from this:**
```yaml
{
   verses: [For god so loved..., Trust in the Lord..., ...],
   references: [John 3:16, Proverbs 3:5-6, ...]
}
```

**to this:**
```yaml
{
   [{
      topic: "Love"
      reference: "John 3:16"
      verse: "For god so loved...",
   },
   {
      topic: "Trusting God"
      reference: "Proverbs 3:5-6"
      verse: "Trust in the Lord...",
   }]
}
```
